import{a as m,i as n,S as L}from"./assets/vendor-B-D547pe.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const i of t)if(i.type==="childList")for(const a of i.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function o(t){const i={};return t.integrity&&(i.integrity=t.integrity),t.referrerPolicy&&(i.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?i.credentials="include":t.crossOrigin==="anonymous"?i.credentials="omit":i.credentials="same-origin",i}function s(t){if(t.ep)return;t.ep=!0;const i=o(t);fetch(t.href,i)}})();async function g(r,e){m.defaults.baseURL="https://pixabay.com";const o=await m.get("/api/",{params:{key:"31908643-2178b12526c513c1beb381d6b",q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:15}});return console.log(o.data),console.log(o.data.totalHits),o.data}const h=document.querySelector(".gallery");function f(r){const e=r.map(({largeImageURL:o,webformatURL:s,tags:t,likes:i,views:a,comments:v,downloads:b})=>`<li class="gallery-item"><a class="gallery-link" href="${o}"><img class="gallery-image" src="${s}" alt="${t}"/></a><ul class="img-info-list">
            <li class="img-info-item">
              <h3 class="img-info-item-header">Likes</h3>
              <p class="img-info-item-value">${i}</p>
            </li>
            <li class="img-info-item">
              <h3 class="img-info-item-header">Views</h3>
              <p class="img-info-item-value">${a}</p>
            </li>
            <li class="img-info-item">
              <h3 class="img-info-item-header">Comments</h3>
              <p class="img-info-item-value">${v}</p>
            </li>
            <li class="img-info-item">
              <h3 class="img-info-item-header">Downloads</h3>
              <p class="img-info-item-value">${b}</p>
            </li>
          </ul></li>`).join("");h.insertAdjacentHTML("beforeend",e)}function k(){h.innerHTML=""}const E=document.querySelector(".form"),d=document.querySelector(".loader");document.querySelector(".gallery");const c=document.getElementById("load-more-btn");E.addEventListener("submit",O);c.addEventListener("click",P);let l=1,u="";const p=15;function O(r){if(r.preventDefault(),k(),c.classList.add("visually-hidden"),u=r.currentTarget.searchText.value.trim(""),u==="")return n.error({theme:"dark",message:"Please, fill out the search field.",backgroundColor:"#EF4040",closeOnClick:!0,position:"topRight",timeout:3e3});d.classList.remove("visually-hidden"),l=1,g(u,l).then(e=>{const o=e.hits;if(o.length===0)return n.error({theme:"dark",message:"Sorry, there are no images matching your search query. Please try again!",backgroundColor:"#EF4040",closeOnClick:!0,position:"topRight",timeout:3e3});f(o),y.refresh(),e.totalHits>=p&&(l+=1,c.classList.remove("visually-hidden"))}).catch(e=>(console.log(e),n.error({theme:"dark",title:"Error!",message:"Sorry, something went wrong.",backgroundColor:"#EF4040",closeOnClick:!0,position:"topRight",timeout:3e3}))).finally(()=>{d.classList.add("visually-hidden")}),r.currentTarget.searchText.value=""}const C={captionDelay:250,captionsData:"alt"};let y=new L(".gallery a",C);function P(r){g(u,l).then(e=>{d.classList.remove("visually-hidden");const o=e.hits,s=e.totalHits,t=S(s,p);if(f(o),y.refresh(),console.log(l),l>=t)return c.classList.add("visually-hidden"),n.info({theme:"light",message:"All the pictures have been loaded.",backgroundColor:"#6c8cff",closeOnClick:!0,position:"bottomRight",timeout:5e3});c.classList.remove("visually-hidden"),l+=1}).catch(e=>(console.log(e),n.error({theme:"dark",title:"Error!",message:"Sorry, something went wrong.",backgroundColor:"#EF4040",closeOnClick:!0,position:"topRight",timeout:3e3}))).finally(()=>{d.classList.add("visually-hidden")})}function S(r,e){return console.log(Math.ceil(r/e)),Math.ceil(r/e)}
//# sourceMappingURL=index.js.map
