import{a as d,S as L,i as a}from"./assets/vendor-B-D547pe.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&i(l)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();async function g(o,t){return d.defaults.baseURL="https://pixabay.com",(await d.get("/api/",{params:{key:"31908643-2178b12526c513c1beb381d6b",q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15}})).data}const f=document.querySelector(".gallery"),b={captionDelay:250,captionsData:"alt"};let E=new L(".gallery a",b);function h(o){const t=o.map(({largeImageURL:s,webformatURL:i,tags:e,likes:r,views:l,comments:p,downloads:v})=>`<li class="gallery-item"><a class="gallery-link" href="${s}"><img class="gallery-image" src="${i}" alt="${e}"/></a><ul class="img-info-list">
            <li class="img-info-item">
              <h3 class="img-info-item-header">Likes</h3>
              <p class="img-info-item-value">${r}</p>
            </li>
            <li class="img-info-item">
              <h3 class="img-info-item-header">Views</h3>
              <p class="img-info-item-value">${l}</p>
            </li>
            <li class="img-info-item">
              <h3 class="img-info-item-header">Comments</h3>
              <p class="img-info-item-value">${p}</p>
            </li>
            <li class="img-info-item">
              <h3 class="img-info-item-header">Downloads</h3>
              <p class="img-info-item-value">${v}</p>
            </li>
          </ul></li>`).join("");f.insertAdjacentHTML("beforeend",t),E.refresh()}function S(){f.innerHTML=""}const k=document.querySelector(".form"),m=document.querySelector(".loader"),C=document.querySelector(".gallery"),c=document.getElementById("load-more-btn");k.addEventListener("submit",w);c.addEventListener("click",O);let n=1,u="";const y=15;async function w(o){o.preventDefault(),S(),c.classList.add("visually-hidden");const t=o.currentTarget,{searchText:s}=t.elements;if(u=s.value.trim(""),u==="")return a.error({theme:"dark",message:"Please, fill out the search field.",backgroundColor:"#EF4040",messageSize:16,closeOnClick:!0,position:"topRight",timeout:3e3});m.classList.remove("visually-hidden"),n=1;try{const{hits:i,totalHits:e}=await g(u,n),r=i;if(r.length===0)return a.error({theme:"dark",message:"Sorry, there are no images matching your search query. Please try again!",backgroundColor:"#EF4040",closeOnClick:!0,position:"topRight",timeout:3e3});h(r),e>y&&c.classList.remove("visually-hidden")}catch(i){return console.log(i),a.error({theme:"dark",title:"Error!",message:"Sorry, something went wrong.",backgroundColor:"#EF4040",messageSize:16,closeOnClick:!0,position:"topRight",timeout:3e3})}finally{m.classList.add("visually-hidden"),t.reset()}}async function O(o){n+=1,c.classList.add("visually-hidden"),m.classList.remove("visually-hidden");try{const{hits:t,totalHits:s}=await g(u,n),i=t,e=Math.ceil(s/y);if(h(i),q(),n>=3)return a.info({theme:"dark",message:"We're sorry, but you've reached the end of the search results.",backgroundColor:"#6c8cff",messageColor:"#fff",messageSize:16,closeOnClick:!0,position:"bottomRight",timeout:5e3});c.classList.remove("visually-hidden")}catch(t){return console.log(t),a.error({theme:"dark",title:"Error!",message:"Sorry, something went wrong.",backgroundColor:"#EF4040",messageSize:16,closeOnClick:!0,position:"topRight",timeout:3e3})}finally{m.classList.add("visually-hidden")}}function q(){const t=C.querySelector(".gallery-item").getBoundingClientRect().height*2;window.scrollBy({top:t,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
